name: hdf5 dev autotools CI

# Triggers the workflow on push or pull request or on demand
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.github/FUNDING.yml'
      - 'doc/**'
      - 'release_docs/**'
      - 'ACKNOWLEDGEMENTS'
      - 'LICENSE**'
      - '**.md'

# Using concurrency to cancel any in-progress job or run
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
    call-release-auto-julia:
        name: "Autotools Julia Workflows"
        uses: ./.github/workflows/julia-auto.yml
        with:
          build_mode: "production"

#  workflow-msys2-autotools:
#    name: "CMake msys2 Workflows"
#    uses: ./.github/workflows/msys2-auto.yml
#    with:
#        build_mode: "production"
#        build_option: "--enable-production"

            
