name: Set env defaults

on: [push, pull_request]
permissions:
  contents: read

jobs:
  set_environment_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Set up common test environment
        run: |
          echo "MY_LINUX_VERSION=ubuntu-latest" >> $GITHUB_ENV
          echo "MY_MACOS_VERSION=macos-latest" >> $GITHUB_ENV
          echo "MY_WINDOWS_VERSION=windows-latest" >> $GITHUB_ENV
          echo "MY_GCC_PACKAGES=gcc-12 g++-12 gfortran-12" >> $GITHUB_ENV
          echo "MY_GCC_COMPILERS=CC=gcc-12 CXX=g++-12 FC=gfortran-12" >> $GITHUB_ENV
          echo "--- GITHUB_ENV ---"
          echo $GITHUB_ENV
